@startuml
actor User
rectangle TemiWebApli{
    (voir Modele) as (modele)
    (demarrer comparaison ) as (compa)
    left to right direction
        (modele) .>(voir resultat):extends
    (compa) .>(voir graphique):extends
    (récuperer TEMI EXCEL)<.(compa):extends
}

left to right direction
User -> (modele)
User --> (compa)


@enduml