TEMI\mainBundle\Entity\Impot:
    type: entity
    table: null
    repositoryClass: TEMI\mainBundle\Repository\ImpotRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cfe:
            type: decimal
            precision: '10'
            scale: '1'
        isImp:
            type: decimal
            precision: '10'
            scale: '1'
        imf:
            type: decimal
            precision: 10
            scale: '1'
        irvm:
            type: decimal
            precision: 10
            scale: '1'
        irc:
            type: decimal
            precision: 10
            scale: '1'
        tvaPetrole:
            type: decimal
            precision: 10
            scale: '1'
            column: tva_petrole
    lifecycleCallbacks: {  }
