hello_the_world:
    path:     /hello-world
    defaults: { _controller: TEMImainBundle:Advert:index }

bye_the_world:
    path:     /bye
    defaults: { _controller: TEMImainBundle:Advert:bye }

temi_platform_home:
    path:     /
    defaults: { _controller: TEMImainBundle:Temi:index }

temi_platform_modele:
    path:     /Modele
    defaults: { _controller: TEMImainBundle:Temi:Modele }

temi_platform_add:
    path:     /ajoutPays
    defaults: { _controller: TEMImainBundle:Temi:ajoutPays }

temi_platform_graph:
    path:     /graph
    defaults: {_controller: TEMImainBundle:Temi:graph }
temi_user_login:
    path:     /Connection
    defaults: { _controller: TEMImainBundle:Connect:connection}
temi_user_sign_up:
    path:     /inscription
    defaults: { _controller: TEMImainBundle:Connect:inscription}
temi_user_logout:
    path:     /Connection
    defaults: { _controller: TEMImainBundle:Connect:deconnection}