hello_the_world:
    path:     /hello-world
    defaults: { _controller: TEMImainBundle:Advert:index }

bye_the_world:
    path:     /bye
    defaults: { _controller: TEMImainBundle:Advert:bye }

temi_platform_home:
    path:     /
    defaults: { _controller: TEMImainBundle:Temi:index }

temi_platform_modele:
    path:     /modele
    defaults: { _controller: TEMImainBundle:Temi:modele }

temi_platform_add:
    path:     /ajoutPays
    defaults: { _controller: TEMImainBundle:Temi:ajoutPays }

temi_platform_graph:
    path:     /graph
    defaults: {_controller: TEMImainBundle:Temi:graph }
