<?php

namespace Proxies\__CG__\TEMI\mainBundle\Entity\Land;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ammortissement extends \TEMI\mainBundle\Entity\Land\Ammortissement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'id', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'construction', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'equipement', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'coefdegressif', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'camion', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'matInformatique', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'matBureau'];
        }

        return ['__isInitialized__', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'id', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'construction', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'equipement', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'coefdegressif', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'camion', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'matInformatique', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Ammortissement' . "\0" . 'matBureau'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ammortissement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstruction($construction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstruction', [$construction]);

        return parent::setConstruction($construction);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstruction', []);

        return parent::getConstruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipement($equipement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipement', [$equipement]);

        return parent::setEquipement($equipement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipement', []);

        return parent::getEquipement();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoefdegressif($coefdegressif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoefdegressif', [$coefdegressif]);

        return parent::setCoefdegressif($coefdegressif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoefdegressif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoefdegressif', []);

        return parent::getCoefdegressif();
    }

    /**
     * {@inheritDoc}
     */
    public function setCamion($camion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCamion', [$camion]);

        return parent::setCamion($camion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCamion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamion', []);

        return parent::getCamion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatInformatique($matInforrmatique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatInformatique', [$matInforrmatique]);

        return parent::setMatInformatique($matInforrmatique);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatInformatique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatInformatique', []);

        return parent::getMatInformatique();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatBureau($matBureau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatBureau', [$matBureau]);

        return parent::setMatBureau($matBureau);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatBureau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatBureau', []);

        return parent::getMatBureau();
    }

}
