<?php

namespace Proxies\__CG__\TEMI\mainBundle\Entity\Land;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Impot extends \TEMI\mainBundle\Entity\Land\Impot implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'id', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'cfe', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'isImp', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'imf', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'irvm', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'irc', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'tvaPetrole'];
        }

        return ['__isInitialized__', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'id', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'cfe', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'isImp', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'imf', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'irvm', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'irc', '' . "\0" . 'TEMI\\mainBundle\\Entity\\Land\\Impot' . "\0" . 'tvaPetrole'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Impot $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCfe($cfe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCfe', [$cfe]);

        return parent::setCfe($cfe);
    }

    /**
     * {@inheritDoc}
     */
    public function getCfe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCfe', []);

        return parent::getCfe();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsImp($isImp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsImp', [$isImp]);

        return parent::setIsImp($isImp);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsImp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsImp', []);

        return parent::getIsImp();
    }

    /**
     * {@inheritDoc}
     */
    public function setImf($imf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImf', [$imf]);

        return parent::setImf($imf);
    }

    /**
     * {@inheritDoc}
     */
    public function getImf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImf', []);

        return parent::getImf();
    }

    /**
     * {@inheritDoc}
     */
    public function setIrvm($irvm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIrvm', [$irvm]);

        return parent::setIrvm($irvm);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrvm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrvm', []);

        return parent::getIrvm();
    }

    /**
     * {@inheritDoc}
     */
    public function setIrc($irc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIrc', [$irc]);

        return parent::setIrc($irc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrc', []);

        return parent::getIrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTvaPetrole($tvaPetrole)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTvaPetrole', [$tvaPetrole]);

        return parent::setTvaPetrole($tvaPetrole);
    }

    /**
     * {@inheritDoc}
     */
    public function getTvaPetrole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTvaPetrole', []);

        return parent::getTvaPetrole();
    }

}
