<?php

namespace TEMI\mainBundle\Repository;

/**
 * ammortissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ammortissementRepository extends \Doctrine\ORM\EntityRepository
{
}
