<?php

namespace TEMI\mainBundle\Repository;

/**
 * ImpotPaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpotPaysRepository extends \Doctrine\ORM\EntityRepository
{
}
