<?php

namespace TEMI\mainBundle\Repository;

/**
 * impotPaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class impotPaysRepository extends \Doctrine\ORM\EntityRepository
{
}
