<?php

namespace TEMI\mainBundle\Repository;

/**
 * ImpotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpotRepository extends \Doctrine\ORM\EntityRepository
{
}
