<?php

namespace TEMI\mainBundle\Repository;

/**
 * InvestissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestissementRepository extends \Doctrine\ORM\EntityRepository
{
}
