<?php

namespace TEMI\mainBundle\Repository;

/**
 * LandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandRepository extends \Doctrine\ORM\EntityRepository
{
    public function insertedLand(){

    }
}
